name: texanroundtable
favicon: null
layout_spectrum: 0.4574278180953115
typography_spectrum: 0.21213881205767393
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7880229614675045
  lightness: 0.8722237490583211
  saturation: 0.39568549767136574
  rhythmicContrast: 0.27210590802133083
purpose: []
